package com.example.common.entry.user;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table permission
 *
 * @mbg.generated do_not_delete_during_merge 2018-01-02 15:48:55
 */
public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permissionId
     *
     * @mbg.generated 2018-01-02 15:48:55
     */
    private Integer permissionId;

    /**
     * Database Column Remarks:
     *   权限唯一编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permissionCode
     *
     * @mbg.generated 2018-01-02 15:48:55
     */
    private String permissionCode;

    /**
     * Database Column Remarks:
     *   权限名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permissionName
     *
     * @mbg.generated 2018-01-02 15:48:55
     */
    private String permissionName;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.remark
     *
     * @mbg.generated 2018-01-02 15:48:55
     */
    private String remark;

    //--------------------------   以下是不保存到数据库的字段        ----------------------
    private String roleCode;

    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permissionId
     *
     * @return the value of permission.permissionId
     *
     * @mbg.generated 2018-01-02 15:48:55
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permissionId
     *
     * @param permissionId the value for permission.permissionId
     *
     * @mbg.generated 2018-01-02 15:48:55
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permissionCode
     *
     * @return the value of permission.permissionCode
     *
     * @mbg.generated 2018-01-02 15:48:55
     */
    public String getPermissionCode() {
        return permissionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permissionCode
     *
     * @param permissionCode the value for permission.permissionCode
     *
     * @mbg.generated 2018-01-02 15:48:55
     */
    public void setPermissionCode(String permissionCode) {
        this.permissionCode = permissionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permissionName
     *
     * @return the value of permission.permissionName
     *
     * @mbg.generated 2018-01-02 15:48:55
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permissionName
     *
     * @param permissionName the value for permission.permissionName
     *
     * @mbg.generated 2018-01-02 15:48:55
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.remark
     *
     * @return the value of permission.remark
     *
     * @mbg.generated 2018-01-02 15:48:55
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.remark
     *
     * @param remark the value for permission.remark
     *
     * @mbg.generated 2018-01-02 15:48:55
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

	public String getRoleCode() {
		return roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}