package com.example.common.entry.user;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table role_permission
 *
 * @mbg.generated do_not_delete_during_merge 2017-12-19 20:11:34
 */
public class RolePermission {
    /**
     * Database Column Remarks:
     *   角色ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.roleId
     *
     * @mbg.generated 2017-12-19 20:11:34
     */
    private Integer roleId;

    /**
     * Database Column Remarks:
     *   权限表ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.permissionId
     *
     * @mbg.generated 2017-12-19 20:11:34
     */
    private Integer permissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.roleId
     *
     * @return the value of role_permission.roleId
     *
     * @mbg.generated 2017-12-19 20:11:34
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.roleId
     *
     * @param roleId the value for role_permission.roleId
     *
     * @mbg.generated 2017-12-19 20:11:34
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.permissionId
     *
     * @return the value of role_permission.permissionId
     *
     * @mbg.generated 2017-12-19 20:11:34
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.permissionId
     *
     * @param permissionId the value for role_permission.permissionId
     *
     * @mbg.generated 2017-12-19 20:11:34
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }
}