package com.example.common.entry.user;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table role
 *
 * @mbg.generated do_not_delete_during_merge 2018-01-02 15:50:03
 */
public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.roleId
     *
     * @mbg.generated 2018-01-02 15:50:03
     */
    private Integer roleId;

    /**
     * Database Column Remarks:
     *   角色唯一编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.roleCode
     *
     * @mbg.generated 2018-01-02 15:50:03
     */
    private String roleCode;

    /**
     * Database Column Remarks:
     *   角色名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.roleName
     *
     * @mbg.generated 2018-01-02 15:50:03
     */
    private String roleName;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.remark
     *
     * @mbg.generated 2018-01-02 15:50:03
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.roleId
     *
     * @return the value of role.roleId
     *
     * @mbg.generated 2018-01-02 15:50:03
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.roleId
     *
     * @param roleId the value for role.roleId
     *
     * @mbg.generated 2018-01-02 15:50:03
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.roleCode
     *
     * @return the value of role.roleCode
     *
     * @mbg.generated 2018-01-02 15:50:03
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.roleCode
     *
     * @param roleCode the value for role.roleCode
     *
     * @mbg.generated 2018-01-02 15:50:03
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.roleName
     *
     * @return the value of role.roleName
     *
     * @mbg.generated 2018-01-02 15:50:03
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.roleName
     *
     * @param roleName the value for role.roleName
     *
     * @mbg.generated 2018-01-02 15:50:03
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.remark
     *
     * @return the value of role.remark
     *
     * @mbg.generated 2018-01-02 15:50:03
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.remark
     *
     * @param remark the value for role.remark
     *
     * @mbg.generated 2018-01-02 15:50:03
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}