package com.example.common.entry.user;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_role
 *
 * @mbg.generated do_not_delete_during_merge 2017-12-19 20:07:15
 */
public class UserRole {
    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.userId
     *
     * @mbg.generated 2017-12-19 20:07:15
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   角色ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.roleId
     *
     * @mbg.generated 2017-12-19 20:07:15
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.userId
     *
     * @return the value of user_role.userId
     *
     * @mbg.generated 2017-12-19 20:07:15
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.userId
     *
     * @param userId the value for user_role.userId
     *
     * @mbg.generated 2017-12-19 20:07:15
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.roleId
     *
     * @return the value of user_role.roleId
     *
     * @mbg.generated 2017-12-19 20:07:15
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.roleId
     *
     * @param roleId the value for user_role.roleId
     *
     * @mbg.generated 2017-12-19 20:07:15
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}