package com.example.common.entry.user;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
 *
 * @mbg.generated do_not_delete_during_merge 2018-01-02 15:46:34
 */
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userId
     *
     * @mbg.generated 2018-01-02 15:46:34
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userName
     *
     * @mbg.generated 2018-01-02 15:46:34
     */
    private String userName;

    /**
     * Database Column Remarks:
     *   昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nickName
     *
     * @mbg.generated 2018-01-02 15:46:34
     */
    private String nickName;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated 2018-01-02 15:46:34
     */
    private String password;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.remark
     *
     * @mbg.generated 2018-01-02 15:46:34
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   6位随机码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.randomCode
     *
     * @mbg.generated 2018-01-02 15:46:34
     */
    private String randomCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userId
     *
     * @return the value of user.userId
     *
     * @mbg.generated 2018-01-02 15:46:34
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userId
     *
     * @param userId the value for user.userId
     *
     * @mbg.generated 2018-01-02 15:46:34
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userName
     *
     * @return the value of user.userName
     *
     * @mbg.generated 2018-01-02 15:46:34
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userName
     *
     * @param userName the value for user.userName
     *
     * @mbg.generated 2018-01-02 15:46:34
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nickName
     *
     * @return the value of user.nickName
     *
     * @mbg.generated 2018-01-02 15:46:34
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nickName
     *
     * @param nickName the value for user.nickName
     *
     * @mbg.generated 2018-01-02 15:46:34
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated 2018-01-02 15:46:34
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated 2018-01-02 15:46:34
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.remark
     *
     * @return the value of user.remark
     *
     * @mbg.generated 2018-01-02 15:46:34
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.remark
     *
     * @param remark the value for user.remark
     *
     * @mbg.generated 2018-01-02 15:46:34
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.randomCode
     *
     * @return the value of user.randomCode
     *
     * @mbg.generated 2018-01-02 15:46:34
     */
    public String getRandomCode() {
        return randomCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.randomCode
     *
     * @param randomCode the value for user.randomCode
     *
     * @mbg.generated 2018-01-02 15:46:34
     */
    public void setRandomCode(String randomCode) {
        this.randomCode = randomCode;
    }
}