package com.example.service.dao.user;


import com.example.common.entry.user.User;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated 2018-01-02 15:46:34
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated 2018-01-02 15:46:34
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated 2018-01-02 15:46:34
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated 2018-01-02 15:46:34
     */
    User selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated 2018-01-02 15:46:34
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated 2018-01-02 15:46:34
     */
    int updateByPrimaryKey(User record);
    
    /**
     * 提供给登录校验
     * @param record
     * @return
     */
    User checkLoginByUser(User record);
    
    /**
     * 获取所有用户
     * @return
     */
    List<User> selectListBySelective(User record);
    
    /**
     * 根据用户名查询用户资料（登录或者校验专用）
     * @param record
     * @return
     */
    User getUserByUserName(User record);
    
}