server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: test-api
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 47.107.46.179
    port: 5672
  redis:
    host: 47.107.46.179
    port: 6379
    #用连接池
    jedis:
      pool:
        min-idle: 0
#    password:
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  messages:
    encoding: UTF-8

eureka:
  instance:
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8079/eureka/
#      defaultZone: http://47.107.46.179:8079/eureka/


#开启hystrix
feign:
  hystrix:
    enabled: true