server:
  port: 8070

spring:
  application:
    name: test-service
  rabbitmq:
    host: 47.107.46.179
    port: 5672
#    username: admin
#    password: secret
    username: guest
    password: guest
    publisher-confirms: true #消息发送到交换机确认机制，是否确认回调
    publisher-returns: true #消息发送到交换机确认机制，是否返回回调
    listener:
      simple:
        acknowledge-mode: manual #采用手动应答
        #concurrency: 1 #指定最小的消费者数量
        #max-concurrency: 1 #指定最大的消费者数量
        retry:
          enabled: true #是否支持重试
      direct:
        acknowledge-mode: manual #采用手动应答
  redis: #redis
    host: 47.107.46.179
    port: 6379
    #用连接池
    jedis:
      pool:
        min-idle: 0
  #    password:
  datasource:
#    url: jdbc:mysql://47.107.46.179:8066/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    url: jdbc:mysql://47.107.46.179:3308/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  druid:
    initial-size: 8
    min-idle: 1
    max-active: 20
    max-wait: 60000
    time-between-eviction-runsMillis: 60000
    min-evictable-idle-timeMillis: 300000
    validation-query: select 'x' FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    use-global-data-source-stat: true

mybatis:
#  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.example.service.model
  type-aliases-package: com.example.common.entry
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

#mapper
#mappers 多个接口时逗号隔开
#mapper:
#  mappers: tk.mybatis.springboot.util.MyMapper
#  not-empty: false
#  i-d-e-n-t-i-t-y: MYSQL

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


customValue:
  tempValue: dev

#swagger配置
swagger:
  enabled: true
  title: spring-boot-starter-swagger
  description: Starter for swagger 2.x
  version: 1.4.0.RELEASE
#  license: Apache License, Version 2.0
#  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
#  termsOfServiceUrl: https://github.com/dyc87112/spring-boot-starter-swagger
#  base-package: com.controller
#  contact:
#    name: temp
#    url: http://blog.didispace.com
#    email: hfxing123@qq.com
#  base-path: /**
#  exclude-path: /error, /ops/**


#  \test\test-service\src\main\java\com\example\service\dao
logging:
  level:
    com:
      example:
        service:
          dao: debug
  #log4j2
  config: classpath:logback-dev.xml

#eureka 配置，指定服务器
eureka:
  instance:
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8069/eureka/
#      defaultZone: http://47.107.46.179/eureka/

#management:
#  health:
#    rabbit:
#      enabled: false

management:
  health:
    rabbit:
      enabled: false
