
spring:
  rabbitmq:
    host: 47.107.46.179
    port: 5672
#    username: admin
#    password: secret
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://47.107.46.179:3307/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  druid:
    initial-size: 8
    min-idle: 1
    max-active: 20
    max-wait: 60000
    time-between-eviction-runsMillis: 60000
    min-evictable-idle-timeMillis: 300000
    validation-query: select 'x' FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    use-global-data-source-stat: true

mybatis:
#  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.service.model
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

#mapper
#mappers 多个接口时逗号隔开
#mapper:
#  mappers: tk.mybatis.springboot.util.MyMapper
#  not-empty: false
#  i-d-e-n-t-i-t-y: MYSQL

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


customValue:
  tempValue: pro


#swagger配置
swagger:
  enabled: true
  title: spring-boot-starter-swagger
  description: Starter for swagger 2.x
  version: 1.4.0.RELEASE
#  license: Apache License, Version 2.0
#  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
#  termsOfServiceUrl: https://github.com/dyc87112/spring-boot-starter-swagger
#  base-package: com.controller
#  contact:
#    name: temp
#    url: http://blog.didispace.com
#    email: hfxing123@qq.com
#  base-path: /**
#  exclude-path: /error, /ops/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8079/eureka/
logging:
  config: classpath:logback-pro.xml